### ISSUE TITLE
Course 01 Project

### ISSUE THREAD

**Issue by shamlawista** [wakqasahmed/course-02-project-blockchain-spec#1]
Hello,

Does anyone have the final project of course 01? (blockchain basics)

**Comment by Rama526** [comment]
Hey, you got any solution, for final project of blockchain basics?
?

**Comment by ufo352** [comment]
Hello friends

There is a problem, I have also tried several times to find a solution, but the most important thing is to do it yourself, why; 

1. on completion of the task, you will receive a code that is changed every time, so this means that my code is no longer valid and it changes every time, so you have to download the program yourself and go through the steps yourself. 

2. if it is during the installation of the program, I recommend to watch this video

Windows: https://www.youtube.com/watch?v=QbmRXJJKsvs 

Macbook/Imac: https://www.youtube.com/watch?v=sNixOS6mHlU

3. you really just have to follow the steps, it's really very simple. You don't have to do any math or any work, it's just to follow the steps.

4. you will only work with VirtualBox and you will receive a code when you finish the task, you will need to write this down separately in a note and send it to Coursera. 

Best Regards
Your friend

**Comment by wakqasahmed** [comment]
> Hello friends
> 
> There is a problem, I have also tried several times to find a solution, but the most important thing is to do it yourself, why;
> 
> 1. on completion of the task, you will receive a code that is changed every time, so this means that my code is no longer valid and it changes every time, so you have to download the program yourself and go through the steps yourself.
> 2. if it is during the installation of the program, I recommend to watch this video
> 
> Windows: https://www.youtube.com/watch?v=QbmRXJJKsvs
> 
> Macbook/Imac: https://www.youtube.com/watch?v=sNixOS6mHlU
> 
> 1. you really just have to follow the steps, it's really very simple. You don't have to do any math or any work, it's just to follow the steps.
> 2. you will only work with VirtualBox and you will receive a code when you finish the task, you will need to write this down separately in a note and send it to Coursera.
> 
> Best Regards
> Your friend

Nicely explained
